export const JournalingGroupData = [
  {
    GroupId: "1",
    title: "Demo title",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molestiae quas vel sint coaxime mollitia,molestiae quas vel sint ",
    Journals: [
      {
        journalId: "1",
        journalTitle: "Demo Title",
        Description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol",
        ans1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans3: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans4: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
      },
      {
        journalId: "2",
        journalTitle: "Demo Title",
        Description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol",
        ans1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans3: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans4: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
      },
      {
        journalId: "3",
        journalTitle: "Demo Title",
        Description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol",
        ans1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans3: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans4: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
      },
      {
        journalId: "4",
        journalTitle: "Demo Title",
        Description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol",
        ans1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans3: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans4: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
      },
    ],
  },
  {
    GroupId: "2",
    title: "Demo title",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molestiae quas vel sint coaxime mollitia,molestiae quas vel sint ",
    Journals: [
      {
        journalId: "1",
        journalTitle: "Demo Title",
        Description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol",
        ans1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans3: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans4: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
      },
      {
        journalId: "2",
        journalTitle: "Demo Title",
        Description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol",
        ans1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans3: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans4: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
      },
      {
        journalId: "3",
        journalTitle: "Demo Title",
        Description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol",
        ans1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans3: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans4: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
      },
      {
        journalId: "4",
        journalTitle: "Demo Title",
        Description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol",
        ans1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans3: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans4: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
      },
    ],
  },
  {
    GroupId: "3",
    title: "Demo title",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molestiae quas vel sint coaxime mollitia,molestiae quas vel sint ",
    Journals: [
      {
        journalId: "1",
        journalTitle: "Demo Title",
        Description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol",
        ans1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans3: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans4: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
      },
      {
        journalId: "2",
        journalTitle: "Demo Title",
        Description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol",
        ans1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans3: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans4: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
      },
      {
        journalId: "3",
        journalTitle: "Demo Title",
        Description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol",
        ans1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans3: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans4: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
      },
      {
        journalId: "4",
        journalTitle: "Demo Title",
        Description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol",
        ans1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans3: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans4: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
      },
    ],
  },
  {
    GroupId: "4",
    title: "Demo title",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molestiae quas vel sint coaxime mollitia,molestiae quas vel sint ",
    Journals: [
      {
        journalId: "1",
        journalTitle: "Demo Title",
        Description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol",
        ans1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans3: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans4: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
      },
      {
        journalId: "2",
        journalTitle: "Demo Title",
        Description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol",
        ans1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans3: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans4: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
      },
      {
        journalId: "3",
        journalTitle: "Demo Title",
        Description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol",
        ans1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans3: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans4: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
      },
      {
        journalId: "4",
        journalTitle: "Demo Title",
        Description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol",
        ans1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans3: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans4: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
      },
    ],
  },
  {
    GroupId: "5",
    title: "Demo title",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molestiae quas vel sint coaxime mollitia,molestiae quas vel sint ",
    Journals: [
      {
        journalId: "1",
        journalTitle: "Demo Title",
        Description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol",
        ans1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans3: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans4: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
      },
      {
        journalId: "2",
        journalTitle: "Demo Title",
        Description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol",
        ans1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans3: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans4: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
      },
      {
        journalId: "3",
        journalTitle: "Demo Title",
        Description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol",
        ans1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans3: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans4: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
      },
      {
        journalId: "4",
        journalTitle: "Demo Title",
        Description:
          "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol",
        ans1: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans2: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans3: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
        ans4: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,molLorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol vv Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,mol ",
      },
    ],
  },
];
