export const USER_FLASHCARD_REQUEST = "USER_FLASHCARD_REQUEST";
export const USER_FLASHCARD_SUCCESS = "USER_FLASHCARD_SUCCESS";
export const USER_FLASHCARD_FAIL = "USER_FLASHCARD_FAIL";

export const USER_CREATE_FLASHCARD_GROUP_REQUEST =
  "USER_CREATE_FLASHCARD_GROUP_REQUEST";
export const USER_CREATE_FLASHCARD_GROUP_SUCCESS =
  "USER_CREATE_FLASHCARD_GROUP_SUCCESS";
export const USER_CREATE_FLASHCARD_GROUP_FAIL =
  "USER_CREATE_FLASHCARD_GROUP_FAIL";

export const USER_FLASHCARD_GROUP_DETAILS_EDIT_REQUEST =
  "USER_FLASHCARD_GROUP_DETAILS_EDIT_REQUEST";
export const USER_FLASHCARD_GROUP_DETAILS_EDIT_SUCCESS =
  "USER_FLASHCARD_GROUP_DETAILS_EDIT_SUCCESS";
export const USER_FLASHCARD_GROUP_DETAILS_EDIT_FAIL = "USER_FLASHCARD_FAIL";

export const USER_ADD_FLASHCARD_REQUEST = "USER_ADD_FLASHCARD_REQUEST";
export const USER_ADD_FLASHCARD_SUCCESS = "USER_ADD_FLASHCARD_SUCCESS";
export const USER_ADD_FLASHCARD_FAIL = "USER_ADD_FLASHCARD_UP_FAIL";

export const USER_FLASHCARD_GROUP_DELETE_REQUEST =
  "USER_FLASHCARD_GROUP_DELETE_REQUEST";
export const USER_FLASHCARD_GROUP_DELETE_SUCCESS =
  "USER_FLASHCARD_GROUP_DELETE_SUCCESS";
export const USER_FLASHCARD_GROUP_DELETE_FAIL =
  "USER_FLASHCARD_GROUP_DELETE_FAIL";

export const USER_FLASHCARD_DELETE_REQUEST = "USER_FLASHCARD_DELETE_REQUEST";
export const USER_FLASHCARD_DELETE_SUCCESS = "USER_FLASHCARD_DELETE_SUCCESS";
export const USER_FLASHCARD_DELETE_FAIL = "USER_FLASHCARD_DELETE_FAIL";
