export const USER_JOURNAL_REQUEST = "USER_JOURNAL_REQUEST";
export const USER_JOURNAL_SUCCESS = "USER_JOURNAL_SUCCESS";
export const USER_JOURNAL_FAIL = "USER_JOURNAL_FAIL";

export const USER_CREATE_JOURNAL_GROUP_REQUEST =
  "USER_CREATE_JOURNAL_GROUP_REQUEST";
export const USER_CREATE_JOURNAL_GROUP_SUCCESS =
  "USER_CREATE_JOURNAL_GROUP_SUCCESS";
export const USER_CREATE_JOURNAL_GROUP_FAIL = "USER_CREATE_JOURNAL_GROUP_FAIL";

export const USER_JOURNAL_GROUP_DETAILS_EDIT_REQUEST =
  "USER_JOURNAL_GROUP_DETAILS_EDIT_REQUEST";
export const USER_JOURNAL_GROUP_DETAILS_EDIT_SUCCESS =
  "USER_JOURNAL_GROUP_DETAILS_EDIT_SUCCESS";
export const USER_JOURNAL_GROUP_DETAILS_EDIT_FAIL = "USER_JOURNAL_FAIL";

export const USER_ADD_JOURNAL_REQUEST = "USER_ADD_JOURNAL_REQUEST";
export const USER_ADD_JOURNAL_SUCCESS = "USER_ADD_JOURNAL_SUCCESS";
export const USER_ADD_JOURNAL_FAIL = "USER_ADD_JOURNAL_UP_FAIL";

export const USER_JOURNAL_GROUP_DELETE_REQUEST =
  "USER_JOURNAL_GROUP_DELETE_REQUEST";
export const USER_JOURNAL_GROUP_DELETE_SUCCESS =
  "USER_JOURNAL_GROUP_DELETE_SUCCESS";
export const USER_JOURNAL_GROUP_DELETE_FAIL = "USER_JOURNAL_GROUP_DELETE_FAIL";

export const USER_JOURNAL_DELETE_REQUEST = "USER_JOURNAL_DELETE_REQUEST";
export const USER_JOURNAL_DELETE_SUCCESS = "USER_JOURNAL_DELETE_SUCCESS";
export const USER_JOURNAL_DELETE_FAIL = "USER_JOURNAL_DELETE_FAIL";
