export const USER_PRIORITY_REQUEST = "USER_PRIORITY_REQUEST";
export const USER_PRIORITY_SUCCESS = "USER_PRIORITY_SUCCESS";
export const USER_PRIORITY_FAIL = "USER_PRIORITY_FAIL";

export const USER_CREATE_PRIORITY_REQUEST = "USER_CREATE_PRIORITY_REQUEST";
export const USER_CREATE_PRIORITY_SUCCESS = "USER_CREATE_PRIORITY_SUCCESS";
export const USER_CREATE_PRIORITY_FAIL = "USER_CREATE_PRIORITY_FAIL";

export const USER_PRIORITY_DETAILS_EDIT_REQUEST =
  "USER_PRIORITY_DETAILS_EDIT_REQUEST";
export const USER_PRIORITY_DETAILS_EDIT_SUCCESS =
  "USER_PRIORITY_DETAILS_EDIT_SUCCESS";
export const USER_PRIORITY_DETAILS_EDIT_FAIL = "USER_PRIORITY_FAIL";

export const USER_PRIORITY_DELETE_REQUEST = "USER_PRIORITY_DELETE_REQUEST";
export const USER_PRIORITY_DELETE_SUCCESS = "USER_PRIORITY_DELETE_SUCCESS";
export const USER_PRIORITY_DELETE_FAIL = "USER_PRIORITY_DELETE_FAIL";
