export const USER_REMAINDER_REQUEST = "USER_REMAINDER_REQUEST";
export const USER_REMAINDER_SUCCESS = "USER_REMAINDER_SUCCESS";
export const USER_REMAINDER_FAIL = "USER_REMAINDER_FAIL";

export const USER_CREATE_REMAINDER_REQUEST = "USER_CREATE_REMAINDER_REQUEST";
export const USER_CREATE_REMAINDER_SUCCESS = "USER_CREATE_REMAINDER_SUCCESS";
export const USER_CREATE_REMAINDER_FAIL = "USER_CREATE_REMAINDER_FAIL";

export const USER_REMAINDER_DETAILS_EDIT_REQUEST =
  "USER_REMAINDER_DETAILS_EDIT_REQUEST";
export const USER_REMAINDER_DETAILS_EDIT_SUCCESS =
  "USER_REMAINDER_DETAILS_EDIT_SUCCESS";
export const USER_REMAINDER_DETAILS_EDIT_FAIL = "USER_REMAINDER_FAIL";

export const USER_REMAINDER_DELETE_REQUEST = "USER_REMAINDER_DELETE_REQUEST";
export const USER_REMAINDER_DELETE_SUCCESS = "USER_REMAINDER_DELETE_SUCCESS";
export const USER_REMAINDER_DELETE_FAIL = "USER_REMAINDER_DELETE_FAIL";

export const USER_MULTIPLE_REMAINDER_DELETE_REQUEST =
  "USER_MULTIPLE_REMAINDER_DELETE_REQUEST";
export const USER_MULTIPLE_REMAINDER_DELETE_SUCCESS =
  "USER_MULTIPLE_REMAINDER_DELETE_SUCCESS";
export const USER_MULTIPLE_REMAINDER_DELETE_FAIL =
  "USER_MULTIPLE_REMAINDER_DELETE_FAIL";
