export const USER_TASK_REQUEST = "USER_TASK_REQUEST";
export const USER_TASK_SUCCESS = "USER_TASK_SUCCESS";
export const USER_TASK_FAIL = "USER_TASK_FAIL";

export const USER_CREATE_TASK_GROUP_REQUEST = "USER_CREATE_TASK_GROUP_REQUEST";
export const USER_CREATE_TASK_GROUP_SUCCESS = "USER_CREATE_TASK_GROUP_SUCCESS";
export const USER_CREATE_TASK_GROUP_FAIL = "USER_CREATE_TASK_GROUP_FAIL";

export const USER_TASK_GROUP_DETAILS_EDIT_REQUEST =
  "USER_TASK_GROUP_DETAILS_EDIT_REQUEST";
export const USER_TASK_GROUP_DETAILS_EDIT_SUCCESS =
  "USER_TASK_GROUP_DETAILS_EDIT_SUCCESS";
export const USER_TASK_GROUP_DETAILS_EDIT_FAIL = "USER_TASK_FAIL";

export const USER_ADD_TASK_REQUEST = "USER_ADD_TASK_REQUEST";
export const USER_ADD_TASK_SUCCESS = "USER_ADD_TASK_SUCCESS";
export const USER_ADD_TASK_FAIL = "USER_ADD_TASK_UP_FAIL";

export const USER_TASK_GROUP_DELETE_REQUEST = "USER_TASK_GROUP_DELETE_REQUEST";
export const USER_TASK_GROUP_DELETE_SUCCESS = "USER_TASK_GROUP_DELETE_SUCCESS";
export const USER_TASK_GROUP_DELETE_FAIL = "USER_TASK_GROUP_DELETE_FAIL";

export const USER_TASK_DELETE_REQUEST = "USER_TASK_DELETE_REQUEST";
export const USER_TASK_DELETE_SUCCESS = "USER_TASK_DELETE_SUCCESS";
export const USER_TASK_DELETE_FAIL = "USER_TASK_DELETE_FAIL";
