export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_HOMEPAGE_VIEW_REQUEST = "USER_HOMEPAGE_VIEW_REQUEST";
export const USER_HOMEPAGE_VIEW_SUCCESS = "USER_HOMEPAGE_VIEW_SUCCESS";
export const USER_HOMEPAGE_VIEW_FAIL = "USER_HOMEPAGE_VIEW_FAIL";

export const USER_FORGOT_PASSWORD_REQUEST = "USER_FORGOT_PASSWORD_REQUEST";
export const USER_FORGOT_PASSWORD_SUCCESS = "USER_FORGOT_PASSWORD_SUCCESS";
export const USER_FORGOT_PASSWORD_FAIL = "USER_FORGOT_PASSWORD_FAIL";

export const USER_VALIDATE_OTP_REQUEST = "USER_VALIDATE_OTP_REQUEST";
export const USER_VALIDATE_OTP_SUCCESS = "USER_VALIDATE_OTP_SUCCESS";
export const USER_VALIDATE_OTP_FAIL = "USER_VALIDATE_OTP_FAIL";

export const USER_CHANGE_PASSWORD_REQUEST = "USER_CHANGE_PASSWORD_REQUEST";
export const USER_CHANGE_PASSWORD_SUCCESS = "USER_CHANGE_PASSWORD_SUCCESS";
export const USER_CHANGE_PASSWORD_FAIL = "USER_CHANGE_PASSWORD_FAIL";

export const USER_SHOW_HIDE_NAVBAR_REQUEST = "USER_SHOW_HIDE_NAVBAR_REQUEST";
export const USER_SHOW_HIDE_NAVBAR_SUCCESS = "USER_SHOW_HIDE_NAVBAR_SUCCESS";
export const USER_SHOW_HIDE_NAVBAR_FAIL = "USER_SHOW_HIDE_NAVBAR_FAIL";

export const USER_SHOW_HIDE_SIDEBAR_REQUEST = "USER_SHOW_HIDE_SIDEBAR_REQUEST";
export const USER_SHOW_HIDE_SIDEBAR_SUCCESS = "USER_SHOW_HIDE_SIDEBAR_SUCCESS";
export const USER_SHOW_HIDE_SIDEBAR_FAIL = "USER_SHOW_HIDE_SIDEBAR_FAIL";
